# Generated by Django 5.1.7 on 2025-04-13 15:53

import api.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FingerprintAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(max_length=50)),
                ('ridge_count', models.IntegerField()),
                ('confidence_score', models.FloatField()),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
                ('analysis_status', models.CharField(default='completed', max_length=50)),
                ('processing_time', models.CharField(max_length=20)),
                ('is_validated', models.BooleanField(default=False)),
                ('analysis_results', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(max_length=50)),
                ('device_name', models.CharField(blank=True, max_length=100, null=True)),
                ('device_model', models.CharField(blank=True, max_length=100, null=True)),
                ('source_details', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.CharField(max_length=20)),
                ('release_date', models.DateTimeField()),
                ('accuracy_score', models.FloatField()),
                ('training_dataset', models.CharField(max_length=255)),
                ('model_parameters', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('framework_used', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('permissions', models.JSONField(default=dict)),
                ('access_level', models.IntegerField(default=1)),
                ('can_provide_expert_feedback', models.BooleanField(default=False)),
                ('can_manage_users', models.BooleanField(default=False)),
                ('can_access_analytics', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ExportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_format', models.CharField(max_length=20)),
                ('export_date', models.DateTimeField(auto_now_add=True)),
                ('file_path', models.CharField(max_length=255)),
                ('is_successful', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to=settings.AUTH_USER_MODEL)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='api.fingerprintanalysis')),
            ],
        ),
        migrations.CreateModel(
            name='FingerprintImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=api.models.fingerprint_upload_path)),
                ('original_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('image_format', models.CharField(blank=True, max_length=10, null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('finger_position', models.CharField(choices=[('thumb', 'Thumb'), ('index', 'Index Finger'), ('middle', 'Middle Finger'), ('ring', 'Ring Finger'), ('pinky', 'Pinky Finger')], max_length=10)),
                ('hand_type', models.CharField(choices=[('left', 'Left Hand'), ('right', 'Right Hand')], max_length=5)),
                ('is_processed', models.BooleanField(default=False)),
                ('preprocessing_status', models.CharField(default='pending', max_length=50)),
                ('title', models.CharField(default='Untitled', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fingerprints', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='api.imagesource')),
            ],
        ),
        migrations.AddField(
            model_name='fingerprintanalysis',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='api.fingerprintimage'),
        ),
        migrations.CreateModel(
            name='AnalysisHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action_performed', models.CharField(max_length=100)),
                ('platform_used', models.CharField(blank=True, max_length=255, null=True)),
                ('device_info', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_history', to=settings.AUTH_USER_MODEL)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='api.fingerprintanalysis')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_history', to='api.fingerprintimage')),
            ],
            options={
                'verbose_name_plural': 'Analysis Histories',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MergedFingerprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merged_image', models.ImageField(upload_to='merged_fingerprints')),
                ('merge_date', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('left_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='left_merges', to='api.fingerprintimage')),
                ('middle_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='middle_merges', to='api.fingerprintimage')),
                ('right_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='right_merges', to='api.fingerprintimage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merged_fingerprints', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='fingerprintanalysis',
            name='model_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses', to='api.modelversion'),
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(max_length=50)),
                ('correction_details', models.TextField(blank=True, null=True)),
                ('corrected_ridge_count', models.IntegerField(blank=True, null=True)),
                ('corrected_classification', models.CharField(blank=True, max_length=50, null=True)),
                ('feedback_date', models.DateTimeField(auto_now_add=True)),
                ('helpfulness_rating', models.IntegerField(blank=True, null=True)),
                ('is_expert_feedback', models.BooleanField(default=False)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='api.fingerprintanalysis')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('related_entity', models.CharField(blank=True, max_length=50, null=True)),
                ('related_entity_id', models.IntegerField(blank=True, null=True)),
                ('action_url', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics')),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('registration_date', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('preferred_platform', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='api.userrole')),
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('expiry_time', models.DateTimeField()),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True)),
                ('device_info', models.TextField(blank=True, null=True)),
                ('platform', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
