# Generated by Django 5.1.7 on 2025-04-13 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='can_perform_analysis',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userrole',
            name='can_upload_images',
            field=models.BooleanField(default=True),
        ),
    ]
