# Generated by Django 5.1.7 on 2025-04-13 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userrole_can_perform_analysis_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrole',
            name='can_perform_analysis',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='can_upload_images',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='permissions',
        ),
    ]
