# Generated by Django 5.1.7 on 2025-05-15 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_userrole_can_perform_analysis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='api.userrole'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='role_name',
            field=models.CharField(choices=[('Regular', 'Regular User'), ('Expert', 'Expert User'), ('Admin', 'Administrator')], default='Regular', max_length=50, unique=True),
        ),
    ]
