# Generated by Django 5.1.7 on 2025-05-30 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_userrole_role_name_expertapplication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mergedfingerprint',
            options={'ordering': ['-merge_date'], 'verbose_name': 'Merged Fingerprint', 'verbose_name_plural': 'Merged Fingerprints'},
        ),
        migrations.AddField(
            model_name='mergedfingerprint',
            name='merge_parameters',
            field=models.JSONField(blank=True, default=dict, help_text='Parameters used for merging'),
        ),
        migrations.AddField(
            model_name='mergedfingerprint',
            name='merge_quality_score',
            field=models.FloatField(blank=True, help_text='Quality score of the merge operation (0-100)', null=True),
        ),
        migrations.AlterField(
            model_name='mergedfingerprint',
            name='left_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merged_as_left', to='api.fingerprintimage'),
        ),
        migrations.AlterField(
            model_name='mergedfingerprint',
            name='merged_image',
            field=models.ImageField(blank=True, null=True, upload_to='merged_fingerprints/'),
        ),
        migrations.AlterField(
            model_name='mergedfingerprint',
            name='middle_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merged_as_middle', to='api.fingerprintimage'),
        ),
        migrations.AlterField(
            model_name='mergedfingerprint',
            name='right_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merged_as_right', to='api.fingerprintimage'),
        ),
        migrations.AlterModelTable(
            name='mergedfingerprint',
            table='api_mergedfingerprint',
        ),
    ]
