# File: docker-compose.yml
# version: '3.8'  <--- DELETE THIS LINE (it should be at the very top of the file)

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root # Consider moving to .env for production
      - POSTGRES_DB=dabafing
    ports:
      - "5433:5432" # Host:Container
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app # Mounts your local backend code into the container
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env # Loads environment variables from this file
    depends_on:
      db:
        condition: service_healthy
    restart: always

volumes:
  postgres_data:
    # driver: local # Optional: explicitly specify local driver